-- istat_transformation.mapping_citta_regione definition

-- Drop table

DROP TABLE istat_transformation.dim_provincia_regione;

CREATE TABLE dwh_progettoandromeda.dim_provincia_regione (
	ids_provincia int4 NULL,
	sigla_territorio varchar(100) null,
	territorio varchar(100) NULL,
	ids_regione int4 null,
	load_timestamp TIMESTAMP null
);

insert into dwh_progettoandromeda.dim_provincia_regione
(ids_provincia, sigla_territorio, territorio, ids_regione, load_timestamp)
values 
(1,	'AG',	'Agrigento',	15,	now()),
(2,	'AL',	'Alessandria',	12,	now()),
(3,	'AN',	'Ancona',	10,	now()),
(4,	'AO',	'Aosta',	19,	now()),
(5,	'AQ',	'L''Aquila',	1,	now()),
(6,	'AR',	'Arezzo',	16,	now()),
(7,	'AP',	'Ascoli Piceno',	10,	now()),
(8,	'AT',	'Asti',	12,	now()),
(9,	'AV',	'Avellino',	4,	now()),
(10,	'BA',	'Bari',	13,	now()),
(11,	'BT',	'Barletta-Andria-Trani',	13,	now()),
(12,	'BL',	'Belluno',	20,	now()),
(13,	'BN',	'Benevento',	4,	now()),
(14,	'BG',	'Bergamo',	9,	now()),
(15,	'BI',	'Biella',	12,	now()),
(16,	'BO',	'Bologna',	5,	now()),
(17,	'BZ',	'BolzanoBozen',	17,	now()),
(18,	'BS',	'Brescia',	9,	now()),
(19,	'BR',	'Brindisi',	13,	now()),
(20,	'CA',	'Cagliari',	14,	now()),
(21,	'CL',	'Caltanissetta',	15,	now()),
(22,	'CB',	'Campobasso',	11,	now()),
(23,	'CE',	'Caserta',	4,	now()),
(24,	'CT',	'Catania',	15,	now()),
(25,	'CZ',	'Catanzaro',	3,	now()),
(26,	'CH',	'Chieti',	1,	now()),
(27,	'CO',	'Como',	9,	now()),
(28,	'CS',	'Cosenza',	3,	now()),
(29,	'CR',	'Cremona',	9,	now()),
(30,	'KR',	'Crotone',	3,	now()),
(31,	'CN',	'Cuneo',	12,	now()),
(32,	'EN',	'Enna',	15,	now()),
(33,	'FM',	'Fermo',	10,	now()),
(34,	'FE',	'Ferrara',	5,	now()),
(35,	'FI',	'Firenze',	16,	now()),
(36,	'FG',	'Foggia',	13,	now()),
(37,	'FC',	'Forlì-Cesena',	5,	now()),
(38,	'FR',	'Frosinone',	7,	now()),
(39,	'GE',	'Genova',	8,	now()),
(40,	'GO',	'Gorizia',	6,	now()),
(41,	'GR',	'Grosseto',	16,	now()),
(42,	'IM',	'Imperia',	8,	now()),
(43,	'IS',	'Isernia',	11,	now()),
(44,	'SP',	'La Spezia',	8,	now()),
(45,	'LT',	'Latina',	7,	now()),
(46,	'LE',	'Lecce',	13,	now()),
(47,	'LC',	'Lecco',	9,	now()),
(48,	'LI',	'Livorno',	16,	now()),
(49,	'LO',	'Lodi',	9,	now()),
(50,	'LU',	'Lucca',	16,	now()),
(51,	'MC',	'Macerata',	10,	now()),
(52,	'MN',	'Mantova',	9,	now()),
(53,	'MS',	'Massa-Carrara',	16,	now()),
(54,	'MT',	'Matera',	2,	now()),
(55,	'VS',	'Medio Campidano',	14,	now()),
(56,	'ME',	'Messina',	15,	now()),
(57,	'MI',	'Milano',	9,	now()),
(58,	'MO',	'Modena',	5,	now()),
(59,	'MB',	'Monza e Brianza',	9,	now()),
(60,	'NA',	'Napoli',	4,	now()),
(61,	'NO',	'Novara',	12,	now()),
(62,	'NU',	'Nuoro',	14,	now()),
(63,	'OR',	'Oristano',	14,	now()),
(64,	'PD',	'Padova',	20,	now()),
(65,	'PA',	'Palermo',	15,	now()),
(66,	'PR',	'Parma',	5,	now()),
(67,	'PV',	'Pavia',	9,	now()),
(68,	'PG',	'Perugia',	18,	now()),
(69,	'PU',	'Pesaro e Urbino',	10,	now()),
(70,	'PE',	'Pescara',	1,	now()),
(71,	'PC',	'Piacenza',	5,	now()),
(72,	'PI',	'Pisa',	16,	now()),
(73,	'PT',	'Pistoia',	16,	now()),
(74,	'PN',	'Pordenone',	6,	now()),
(75,	'PZ',	'Potenza',	2,	now()),
(76,	'PO',	'Prato',	16,	now()),
(77,	'RG',	'Ragusa',	15,	now()),
(78,	'RA',	'Ravenna',	5,	now()),
(79,	'RC',	'Reggio Calabria',	3,	now()),
(80,	'RE',	'Reggio Emilia',	5,	now()),
(81,	'RI',	'Rieti',	7,	now()),
(82,	'RN',	'Rimini',	5,	now()),
(83,	'RM',	'Roma',	7,	now()),
(84,	'RO',	'Rovigo',	20,	now()),
(85,	'SA',	'Salerno',	4,	now()),
(86,	'SS',	'Sassari',	14,	now()),
(87,	'SV',	'Savona',	8,	now()),
(88,	'SI',	'Siena',	16,	now()),
(89,	'SR',	'Siracusa',	15,	now()),
(90,	'SO',	'Sondrio',	9,	now()),
(91,	'SU',	'Sud Sardegna',	14,	now()),
(92,	'TA',	'Taranto',	13,	now()),
(93,	'TE',	'Teramo',	1,	now()),
(94,	'TR',	'Terni',	18,	now()),
(95,	'TO',	'Torino',	12,	now()),
(96,	'TP',	'Trapani',	15,	now()),
(97,	'TN',	'Trento',	17,	now()),
(98,	'TV',	'Treviso',	20,	now()),
(99,	'TS',	'Trieste',	6,	now()),
(100,	'UD',	'Udine',	6,	now()),
(101,	'VA',	'Varese',	9,	now()),
(102,	'VE',	'Venezia',	20,	now()),
(103,	'VB',	'Verbano-Cusio-Ossola',	12,	now()),
(104,	'VC',	'Vercelli',	12,	now()),
(105,	'VR',	'Verona',	20,	now()),
(106,	'VV',	'Vibo Valentia',	3,	now()),
(107,	'VI',	'Vicenza',	20,	now()),
(108,	'VT',	'Viterbo',	7,	now())